### PR TITLE
Unicode support for pexpect

### PR DESCRIPTION
**Pull request by jquast**
This fork includes an incremental decoder for child process output and terminal keyboard input, so that encodings such as utf-8 may be used.

Some other various changes made along the way:
 spelling - use 'written' instead of 'writen' in backend method names.
 refactor - replace duplication of call to '__interact_written' around line 1658
 refactor - move static read size '100' to argument of __interact_read, to assist in documenting "magic numbers".

### CODE REVIEW

**Comment by takluyver** [comment]
There's a design question here about how to handle unicode versus bytes APIs. pexpect currently expects and returns byte strings. My [pexpect-u fork](https://bitbucket.org/takluyver/pexpect/overview), renamed the current spawn class to `spawnb` (b for bytes), and made a new `spawn` subclass to accept and return unicode. The rationale was that trivial uses of pexpect are then easily portable to Python 3, because you can keep using native strings with `spawn()`, but I'm not sure now that this was the best approach. It looks like you've changed the `spawn` class to accept and return unicode, but not left any bytes interface - is that accurate?

Another approach would be to leave spawn as a bytes interface and have a `spawnu` class with a unicode interface. That's less convenient for porting trivial uses to Python 3, but it provides greater consistency for more advanced use cases, and doesn't risk changing the behaviour on Python 2.

**Comment by jquast** [comment]
"but not left any bytes interface - is that accurate?" -- yes.

I had the very same thoughts during implementation. I can think of only a single use-case for retaining the bytes interface -- say somebody wants to write a pexpect script to "cat" out .jpg or other binary files, and read them in as they are. Pretty strange, but possible with a bytes interface, whereas this unicode-aware would probably through a UnicodeDecodeError at some point, when run up against garbage, such as might be found in /dev/urandom.

Ultimately its up to Noah. Or I suppose one of us (I vote you, haha) to maintain some officially renamed fork for py3 onward ?

**Comment by takluyver** [comment]
You also might run some text-based program where you don't know what encoding it will use - not everything respects the various environment variables. That case could be resolved by having an `errors` parameter that's passed through to the encode/decode methods. But I think it is worth retaining a bytes interface - ultimately, terminals do handle bytes, and encodings are a convention that sits on top of that.

I'd love to get @noahspurrier 's thoughts, but I don't think he has much time to work on open source stuff at present. I'm kind of the reluctant owner of a fork already (at least Fedora is actually shipping my fork instead of pexpect), but I don't really use pexpect directly myself: I work on IPython, which uses pexpect in fairly simple ways, and I wanted it to work on Python 3. So I don't feel like I understand it well enough to make important design decisions about it.

**Comment by takluyver** [comment]
@jquast : I'm thinking of making another fork of pexpect, being more rigorous with it than I was with my earlier fork. I'm leaning towards leaving `spawn` as the bytes interface, and having `spawnu` (or `uspawn`?) as the unicode interface. Are you interested in helping me to maintain this?

**Comment by jquast** [comment]
Certainly, I'm willing to help share responsibility of maintaining a fork, i nearly put mine on pypi as well. Let me know where you need a hand (perhaps by creating issues as TODO items in the new github project repo).

I certainly do plan to be active on github, pypi, and terminal programming in general in the coming years, so i don't mind if I get roped up on pexpect once in a while, I have great knowledge in the areas that pexpect touches on.

Suggestions:
- bump the major release to 3.0 to indicate python 3 support, and to bypass the "-nm" dev branch that is versioned as 2.6.
- ensure the primary description (the one pypi displays when searching for 'expect') contains something like: "Unicode-aware and python3 fork of pexpect", so it is clear here. Currently pexpect-u is indistinguishable in search results.
- convert doc/ to reStructuredText format, and host the new documents automatically on "readthedocs.org"
  -- this will also need to contain documentation about spawnu().
  -- Other document cleanup: point to the github page for issue reporting/feature requests/patch submissions, instead of sourceforge, yet make it clear where this codebase was forked from, and when it was last released (2008).
- I'll add my "cp437 shell" example, and also try to think of something else as an example for dealing with terminal programs in encodings other than ascii, perhaps driving the vim editor on the utf-8 demo file by Markus Kuhn ( http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt ).

**Comment by takluyver** [comment]
OK, great. I'm going to call it pexpected, for the lack of any more inspiring name.

**Comment by noahspurrier** [comment]
I could also turn over ownership of the pexpect project to someone else, or add managers, or whatever mechanism GitHub uses to add push/merge permission.

My wife just gave birth to our first child. Plus with my new job I had been having a hard time managing this project even before the baby was born. I have even less time or sleep now that have a baby girl to cuddle and play with.

I hate to be an absentee owner, so I'd be happy to release this to others who can better keep it going.

## 

Noah Spurrier noah@noah.org

**Comment by takluyver** [comment]
Hi Noah! I've made a pexpected organisation on Github with a copy of the repo: https://github.com/pexpected/pexpect - the permissions are already set up, and since most of the history (issues etc.) isn't on Github anyway, I think it's best if we continue maintenance of it under that organisation.

What would be helpful is if you could add me to the maintainers on PyPI, so I can make new releases. If you go to https://pypi.python.org/pypi/pexpect and log in, you should see a 'roles' link just under the title. My PyPI username is takowl.

Likewise, but less importantly, I'd like to get control of pexpect.sourceforge.net, so I can make sure it's up to date. My username on sourceforge is also takowl, so could you add that to the project?

Finally, the top result on Google for pexpect is your wiki page (http://www.noah.org/wiki/pexpect). Would you be happy to add a redirect somewhere, when we've got somewhere complete to redirect to? I've started creating docs at http://pexpected.readthedocs.org/en/latest/ (we may rename that to pexpect if it's to be the official project).

**Comment by takluyver** [comment]
For anyone reading this later: @jquast and I are now maintaining pexpect at https://github.com/pexpect/pexpect , and unicode support is included. :-)

**Pull request closed without merging**
